#!/bin/bash

if [ -z "$PYFILE" ] then
  echo "Error: PYFILE environment variable not set."
  exit 1
fi

# Compile the Python script
python3 -m py_compile "$PYFILE"

# Check if compilation was successful
if [ $? -eq 0 ]; then
  compiled_file="${PYFILE}c"
  echo "Compiling $PYFILE ..."
  mv "__pycache__/$compiled_file" "$compiled_file"
  echo "Compilation successful."
else
  echo "Compilation failed."
fi

